{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-extractor-1.3.1.aar",
          "url": "media3-extractor-1.3.1.aar",
          "size": 753189,
          "sha512": "12d82beaba721457b71a2024dd91841816fd1083e6df200510469f97d10b71382e967d58528ba2a520a65f60e23e791085e4600cbf3729883a151259ae4da128",
          "sha256": "54400e411960da947d85567bbce3e752fade6bcb7d075c122a4e2cd05379dc62",
          "sha1": "305aa48d79fbbc3a450c53b3e905145a921080b7",
          "md5": "272e7c92dc3a278f5b91f9feb0621498"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.3.1.aar",
          "url": "media3-extractor-1.3.1.aar",
          "size": 753189,
          "sha512": "12d82beaba721457b71a2024dd91841816fd1083e6df200510469f97d10b71382e967d58528ba2a520a65f60e23e791085e4600cbf3729883a151259ae4da128",
          "sha256": "54400e411960da947d85567bbce3e752fade6bcb7d075c122a4e2cd05379dc62",
          "sha1": "305aa48d79fbbc3a450c53b3e905145a921080b7",
          "md5": "272e7c92dc3a278f5b91f9feb0621498"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.3.1-sources.jar",
          "url": "media3-extractor-1.3.1-sources.jar",
          "size": 629224,
          "sha512": "8c47017478ef906cd0e561cf373a93dc9560739a8c8d775f9daa285cd1895a05b6d455746b612de1702eadd54d6df7525a7bd5192e21f93bb40e20fbb5397f46",
          "sha256": "daf71df602d948b5968bfa907601a8b549094bd820821d1d0b1e5020757db7b2",
          "sha1": "94121531f961b8bc323a226aa12a3623526fbc06",
          "md5": "6830a18eabe4f23d85761935188bbfd1"
        }
      ]
    }
  ]
}
