{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-container-1.3.1.aar",
          "url": "media3-container-1.3.1.aar",
          "size": 23300,
          "sha512": "5085cb28c0670be961fb73a8c272948231a4668dea66e19cd7e238c3cca2fa7d555df065ba828c4f474059ff1dd9b4299f9e72119e47b9fb22d5bc4274d73b2b",
          "sha256": "c6103c11666e03ceabeb6454b5bf0b9b51fdc93647f84dd02ee869a9c086269e",
          "sha1": "029e6a73a0073a66b8608b619047adbeec17a4d1",
          "md5": "c4a306b24c42c4a4d318eb9ce4f2fd28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.3.1.aar",
          "url": "media3-container-1.3.1.aar",
          "size": 23300,
          "sha512": "5085cb28c0670be961fb73a8c272948231a4668dea66e19cd7e238c3cca2fa7d555df065ba828c4f474059ff1dd9b4299f9e72119e47b9fb22d5bc4274d73b2b",
          "sha256": "c6103c11666e03ceabeb6454b5bf0b9b51fdc93647f84dd02ee869a9c086269e",
          "sha1": "029e6a73a0073a66b8608b619047adbeec17a4d1",
          "md5": "c4a306b24c42c4a4d318eb9ce4f2fd28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.3.1-sources.jar",
          "url": "media3-container-1.3.1-sources.jar",
          "size": 18971,
          "sha512": "eaf274de9d2f9f5f2beef6b827195c9425d325089fbe9efb4da5c0bc1ce7abbb7d0f54911725f1e755bced921d072908036ab13cae37083fcf7e6df858573d08",
          "sha256": "65c948cc02525e8a88837b655a7b31f2ae6912bcbc4bc9d7acb734f2522aa540",
          "sha1": "b4a6a1f001b50570130d9b7ffaa1c008cf723f05",
          "md5": "b4aa17ee14df6f5111dd68cfc5c6ada5"
        }
      ]
    }
  ]
}
