{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.3.1.aar",
          "url": "media3-exoplayer-1.3.1.aar",
          "size": 1399676,
          "sha512": "32e0c73d7dfb5f7f66bfaa3c41adda1b0c13035ced1c3576f3e83f35e97b1254320c86c70ab94aca23561d373bb8ee899780e375934c5791514ce09667808dfb",
          "sha256": "00c4be0107fcb95ce62d5f255e0e07b169f25bfcda820054888e26a89bf0647f",
          "sha1": "2b4073ce441807cb083f7a16de94b2b80374d832",
          "md5": "f9ecf5c45c8d43faa41d7646e56b0797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.3.1.aar",
          "url": "media3-exoplayer-1.3.1.aar",
          "size": 1399676,
          "sha512": "32e0c73d7dfb5f7f66bfaa3c41adda1b0c13035ced1c3576f3e83f35e97b1254320c86c70ab94aca23561d373bb8ee899780e375934c5791514ce09667808dfb",
          "sha256": "00c4be0107fcb95ce62d5f255e0e07b169f25bfcda820054888e26a89bf0647f",
          "sha1": "2b4073ce441807cb083f7a16de94b2b80374d832",
          "md5": "f9ecf5c45c8d43faa41d7646e56b0797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.3.1-sources.jar",
          "url": "media3-exoplayer-1.3.1-sources.jar",
          "size": 1021178,
          "sha512": "2b75c2a37b3df3e3ff277a7f0904aea753329905799f60321ab31c6f4f9e5f5988cc5713c55f84469e09fe2c0fcf65452a567fda3ee569bf9eebab7a3b517450",
          "sha256": "c30282058a61aa6934ca6b2eaeb47383e233622fbda98977a8893c914f2d5907",
          "sha1": "2d8f2d72c538c1f07fa8ace328a47e69a35cd144",
          "md5": "efb6412ccb0c3f52ad5268748a51197a"
        }
      ]
    }
  ]
}
