{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-ui-1.3.1.aar",
          "url": "media3-ui-1.3.1.aar",
          "size": 434525,
          "sha512": "5792a81c1b1646eb8a0eeac8a42db86da3f64ce1f5f7804bc6d10924ac49e960d67b3ffba3edb8221b640d3f6fdcb0d185e96c47c6ed72acf0305d50ca9e7f80",
          "sha256": "a8d206f395838a06b82b0789e7200868dabb26b9c7207e98cc3b3196041c1c9d",
          "sha1": "97d6136ea0c4942f67fccdfb77c5099fec02c4c0",
          "md5": "742451010c9ba15eff3fbde7fa250073"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.3.1.aar",
          "url": "media3-ui-1.3.1.aar",
          "size": 434525,
          "sha512": "5792a81c1b1646eb8a0eeac8a42db86da3f64ce1f5f7804bc6d10924ac49e960d67b3ffba3edb8221b640d3f6fdcb0d185e96c47c6ed72acf0305d50ca9e7f80",
          "sha256": "a8d206f395838a06b82b0789e7200868dabb26b9c7207e98cc3b3196041c1c9d",
          "sha1": "97d6136ea0c4942f67fccdfb77c5099fec02c4c0",
          "md5": "742451010c9ba15eff3fbde7fa250073"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.3.1-sources.jar",
          "url": "media3-ui-1.3.1-sources.jar",
          "size": 112293,
          "sha512": "3bea9579a30fa97ab70167e95c7fa0e773eb6a1aa1df9ae08a531cf88236b453b80440f0e31d1fa09e1ee003cfe2cab298028f7e9ae6f71e113c7e3ff3044913",
          "sha256": "c3d8d9a0c76996f07e9978e9e1176e344783b93ab3967d9c8b23ea414171a747",
          "sha1": "f60799515748ddbd80ea844ba3799f6ed670f002",
          "md5": "c75dbe4543f8d8d3234b00c087b06b9f"
        }
      ]
    }
  ]
}
