{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decoder-1.3.1.aar",
          "url": "media3-decoder-1.3.1.aar",
          "size": 18190,
          "sha512": "f584408e68627de9ab1be2cc6c5adb85a77ab9a858666fc27663b0c974ee9249d030fa1d433d9c91b65ef2671dc8e454e462eb1848f3d59fa27846c1dd067baf",
          "sha256": "c4799cd411061a654ad9c73fbc3d1a95945fce40f1bbceaf219e17b8a56fa1c1",
          "sha1": "41c34c9b51b6a9023702c051ae8fdef80e749d7b",
          "md5": "9679ce35fdcc82cf83692adca5431311"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.3.1.aar",
          "url": "media3-decoder-1.3.1.aar",
          "size": 18190,
          "sha512": "f584408e68627de9ab1be2cc6c5adb85a77ab9a858666fc27663b0c974ee9249d030fa1d433d9c91b65ef2671dc8e454e462eb1848f3d59fa27846c1dd067baf",
          "sha256": "c4799cd411061a654ad9c73fbc3d1a95945fce40f1bbceaf219e17b8a56fa1c1",
          "sha1": "41c34c9b51b6a9023702c051ae8fdef80e749d7b",
          "md5": "9679ce35fdcc82cf83692adca5431311"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-1.3.1-sources.jar",
          "url": "media3-decoder-1.3.1-sources.jar",
          "size": 19371,
          "sha512": "d433ad8d85893be768b8f435746c34d53f0d3b04737b0434c4bf01d1a2712e48a3893ce5caf9aa58eedf6eb3c9b00ed6fbda6e6db9678c45d3681142087ff55e",
          "sha256": "c1f395a3664c144b43142194ee4a528899b64e65ab8b0033a55df21dffd2577b",
          "sha1": "fa405fb0d6b3afe5f1e06fbb5a514e30253f6de1",
          "md5": "acd5d29edfe7036cd05b577e79c1614e"
        }
      ]
    }
  ]
}
