{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.3.1.aar",
          "url": "media3-exoplayer-hls-1.3.1.aar",
          "size": 166691,
          "sha512": "c61b041e7e7d4c1d82fbbb3cd90df77da16bb8790c19940152a9d47281d2b3bf6b2a5657f8014f0e9b75b0276fd65b96e22046fd531eb2ca8168bba63975005e",
          "sha256": "2201136502bb64d024002f41cb33f209902ee548262767141af6d52a75a1816c",
          "sha1": "98cc98ad0b8af76649126f5fb4a5bb1c5e7abf6b",
          "md5": "122ca017bb110b631615f4284aede084"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.3.1.aar",
          "url": "media3-exoplayer-hls-1.3.1.aar",
          "size": 166691,
          "sha512": "c61b041e7e7d4c1d82fbbb3cd90df77da16bb8790c19940152a9d47281d2b3bf6b2a5657f8014f0e9b75b0276fd65b96e22046fd531eb2ca8168bba63975005e",
          "sha256": "2201136502bb64d024002f41cb33f209902ee548262767141af6d52a75a1816c",
          "sha1": "98cc98ad0b8af76649126f5fb4a5bb1c5e7abf6b",
          "md5": "122ca017bb110b631615f4284aede084"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.3.1-sources.jar",
          "url": "media3-exoplayer-hls-1.3.1-sources.jar",
          "size": 122134,
          "sha512": "1001c8d5321952a23b539229d33ec50a9ed36887adfdba000d123fee53b6a59b6b4481938d29c378eaf401de35c81687e0608920dd8a0501df8d4a445caf18b4",
          "sha256": "11ebda359b1efd27de2d4c7c0cd92b3f0f2f26af2c0e8d90f5d5d7fd6ec668f7",
          "sha1": "488950f57399f2044f4bf721165e56d5318bc90d",
          "md5": "b9b7ad30621dae0573729b6c167afe47"
        }
      ]
    }
  ]
}
