{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-datasource-1.3.1.aar",
          "url": "media3-datasource-1.3.1.aar",
          "size": 161672,
          "sha512": "6dff16b029b82eabf67b194a37c44f2b4c43eada0ba6d84477cf8d5aed045bea729b83edf198fbb0caea5dd91b38cda063dfc7cf4f992fdb1de595289c2de1db",
          "sha256": "ad94437e3c3dc5b9fb4a5c2dc64aa912a91125519742ec2fc3ae9ebfacc62381",
          "sha1": "f142a77bd9fc269a0214144feb77ba59b1417358",
          "md5": "804125be6af06f9d1cb081924ecf5584"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.3.1.aar",
          "url": "media3-datasource-1.3.1.aar",
          "size": 161672,
          "sha512": "6dff16b029b82eabf67b194a37c44f2b4c43eada0ba6d84477cf8d5aed045bea729b83edf198fbb0caea5dd91b38cda063dfc7cf4f992fdb1de595289c2de1db",
          "sha256": "ad94437e3c3dc5b9fb4a5c2dc64aa912a91125519742ec2fc3ae9ebfacc62381",
          "sha1": "f142a77bd9fc269a0214144feb77ba59b1417358",
          "md5": "804125be6af06f9d1cb081924ecf5584"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.3.1-sources.jar",
          "url": "media3-datasource-1.3.1-sources.jar",
          "size": 132643,
          "sha512": "1ae3a1c6d421570a2fda3e780013b0a7fd81184b8aa6a6aed083f41f8b668363eac71062ffe09c073c15f14065fd2a5a818a8c9681a3c4f6deb990696cd1bc08",
          "sha256": "58e4a206306d3003f4a48ede3afcdcfed401f912eff050f992b4635fe0a5e4fa",
          "sha1": "1634d249e413ae5bf333868a2a50d0c1dc3ff963",
          "md5": "fe7cf2769b6f3ead8bdb86005cb97b33"
        }
      ]
    }
  ]
}
