{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.3.1.aar",
          "url": "media3-common-1.3.1.aar",
          "size": 484769,
          "sha512": "87d5588ffb5507ad31f9324f35b527042ade41b3b1e31b5d3364d4317cf3edc11d7fc8b79c3f55c038bc83d0406124b3f730d644b3412c70723f417296919bb0",
          "sha256": "40cf8c6c07f75afd0b213d694fd7ac478c726a94e64fa7ac1833c17752f3e6f4",
          "sha1": "1878d907bf61eb04bd9d933bf5389f7dcedce0b8",
          "md5": "0de064660acd2c21078f1d018d4cc075"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.3.1.aar",
          "url": "media3-common-1.3.1.aar",
          "size": 484769,
          "sha512": "87d5588ffb5507ad31f9324f35b527042ade41b3b1e31b5d3364d4317cf3edc11d7fc8b79c3f55c038bc83d0406124b3f730d644b3412c70723f417296919bb0",
          "sha256": "40cf8c6c07f75afd0b213d694fd7ac478c726a94e64fa7ac1833c17752f3e6f4",
          "sha1": "1878d907bf61eb04bd9d933bf5389f7dcedce0b8",
          "md5": "0de064660acd2c21078f1d018d4cc075"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.3.1-sources.jar",
          "url": "media3-common-1.3.1-sources.jar",
          "size": 398268,
          "sha512": "1c5712a8b9568b232300c5f6447d163ca6f832c337cdef7d5322a64e551e38e79073b6fce44eb5362916703da0fd882a7f6a79ef8df6172f5161296a7c34aa3b",
          "sha256": "3fb88f811181244af2dccf8a01fb5641faf4e8d2e5500d7b889197e444ec5cbc",
          "sha1": "014e5678a48b564665536bbc431b8f6bb8dc5811",
          "md5": "d51741c674806534ed28d47524222bce"
        }
      ]
    }
  ]
}
